version: 2
jobs:
  build:
    environment:
      CICA_DEVELOPMENT: cica-development
    steps:
      - name: Build image
      - run:
          command: |
             docker built -t cica/online ../
             docker tag cica/online:latest 926803513772.dkr.ecr.eu-west-1.amazonaws.com/cica/cicadevelopment:circleci-test
      - name: authenticate with ECR
      - run:
          command: |
            ./.circleci/auth-docker.sh

  push:
    steps:
      - name: Push to ECR
      - run:
          command: |
             docker push 926803513772.dkr.ecr.eu-west-1.amazonaws.com/cica/cicadevelopment:circleci-test


workflows:
  version: 2
  one_and_two:
    jobs:
      - build:
      - push:
          requires:
            - build
